name: flutter_dependencies
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  flutter_modular: ^5.0.3
  modular_interfaces: ^2.0.2
  freezed_annotation: ^2.1.0
  logger: ^1.1.0
  equatable: ^2.0.3
  dotted_border:
  google_fonts: ^2.3.1
  shared_preferences: ^2.0.13
  http: ^0.13.4
  dio: ^4.0.4
  dropdown_search: ^2.0.1
  mask_text_input_formatter: ^2.3.0
  intl: ^0.17.0
  cpf_cnpj_validator: ^2.0.0
  image_picker: ^0.8.5
  file_picker: ^4.5.1
  flutter_bloc: ^8.0.1
  mime_type: ^1.0.0
  badges: ^2.0.3
  loader_overlay: ^2.0.7
  provider:
  nsj_login:
    git:
      url: git@github.com:Nasajon/NasajonUI-Flutter-Login.git
      path: nsj_login
  download: ^0.0.1+1
  path_provider: ^2.0.11
  dartz: ^0.10.1
  slang: ^2.7.0
  slang_flutter: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.2.0
  modular_test:
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
