library dependencies;

export 'package:freezed_annotation/freezed_annotation.dart';
export 'package:flutter_modular/flutter_modular.dart' hide Default;
export 'package:modular_interfaces/modular_interfaces.dart';
export 'package:flutter_localizations/flutter_localizations.dart';
export 'package:equatable/equatable.dart';
export 'package:dotted_border/dotted_border.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:http/http.dart' hide MultipartFile;
export 'package:dio/dio.dart' hide Response, Headers;
export 'package:dropdown_search/dropdown_search.dart';
export 'package:mask_text_input_formatter/mask_text_input_formatter.dart';
export 'package:intl/intl.dart';
export 'package:cpf_cnpj_validator/cpf_validator.dart';
export 'package:cpf_cnpj_validator/cnpj_validator.dart';
export 'package:image_picker/image_picker.dart';
export 'package:file_picker/file_picker.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:mime_type/mime_type.dart';
export 'package:badges/badges.dart';
export 'package:loader_overlay/loader_overlay.dart';
export 'package:provider/provider.dart' hide ErrorBuilder;
export 'package:nsj_login/nsj_login.dart';
export 'package:download/download.dart';
export 'package:path_provider/path_provider.dart';
export 'package:logger/logger.dart';
export 'package:flutter_dotenv/flutter_dotenv.dart' hide Parser;
export 'package:dartz/dartz.dart' show Either, Right, Left, Unit, unit;
export 'package:slang/slang.dart';
export 'package:slang_flutter/slang_flutter.dart';
export 'package:retrofit/retrofit.dart';
export 'package:lottie/lottie.dart';
export 'package:auto_size_text/auto_size_text.dart';
export 'package:mask_text_input_formatter/mask_text_input_formatter.dart';
